version: '3.8'

networks:
  stoa:

services:
  stoa0:
    image: github.com/vontikov/stoa:0.0.1
    hostname: stoa0
    command: stoa -log-level debug -bootstrap stoa0,stoa1,stoa2
    networks:
      - stoa
  stoa1:
    image: github.com/vontikov/stoa:0.0.1
    hostname: stoa1
    command: stoa -log-level debug
    networks:
      - stoa
  stoa2:
    image: github.com/vontikov/stoa:0.0.1
    hostname: stoa2
    command: stoa -log-level debug
    networks:
      - stoa

  client0:
    image: github.com/vontikov/stoa-example:0.0.1
    command: stoa-example -log-level debug -bootstrap stoa0,stoa1,stoa2
    networks:
      - stoa
