// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: plugin.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _plugin_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on QueueEntry with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *QueueEntry) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		return QueueEntryValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
	}

	if len(m.GetValue()) < 1 {
		return QueueEntryValidationError{
			field:  "Value",
			reason: "value length must be at least 1 bytes",
		}
	}

	// no validation rules for TtlMillis

	return nil
}

// QueueEntryValidationError is the validation error returned by
// QueueEntry.Validate if the designated constraints aren't met.
type QueueEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueueEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueueEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueueEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueueEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueueEntryValidationError) ErrorName() string { return "QueueEntryValidationError" }

// Error satisfies the builtin error interface
func (e QueueEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueueEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueueEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueueEntryValidationError{}

// Validate checks the field values on DictionaryEntry with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *DictionaryEntry) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		return DictionaryEntryValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
	}

	if len(m.GetKey()) < 1 {
		return DictionaryEntryValidationError{
			field:  "Key",
			reason: "value length must be at least 1 bytes",
		}
	}

	if len(m.GetValue()) < 1 {
		return DictionaryEntryValidationError{
			field:  "Value",
			reason: "value length must be at least 1 bytes",
		}
	}

	// no validation rules for TtlMillis

	return nil
}

// DictionaryEntryValidationError is the validation error returned by
// DictionaryEntry.Validate if the designated constraints aren't met.
type DictionaryEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictionaryEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictionaryEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictionaryEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictionaryEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictionaryEntryValidationError) ErrorName() string { return "DictionaryEntryValidationError" }

// Error satisfies the builtin error interface
func (e DictionaryEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDictionaryEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictionaryEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictionaryEntryValidationError{}
