// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// StoaClient is the client API for Stoa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoaClient interface {
	QueueSize(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Value, error)
	QueueClear(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Empty, error)
	QueueOffer(ctx context.Context, in *Value, opts ...grpc.CallOption) (*Result, error)
	QueuePoll(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Value, error)
	QueuePeek(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Value, error)
	DictionarySize(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Value, error)
	DictionaryClear(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Empty, error)
	DictionaryPutIfAbsent(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Result, error)
	DictionaryPut(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Value, error)
	DictionaryGet(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error)
	DictionaryRemove(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Result, error)
	DictionaryScan(ctx context.Context, in *Name, opts ...grpc.CallOption) (Stoa_DictionaryScanClient, error)
	MutexTryLock(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Result, error)
	MutexUnlock(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Result, error)
	Keep(ctx context.Context, opts ...grpc.CallOption) (Stoa_KeepClient, error)
}

type stoaClient struct {
	cc grpc.ClientConnInterface
}

func NewStoaClient(cc grpc.ClientConnInterface) StoaClient {
	return &stoaClient{cc}
}

func (c *stoaClient) QueueSize(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/github.com.vontikov.stoa.v1.Stoa/QueueSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoaClient) QueueClear(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/github.com.vontikov.stoa.v1.Stoa/QueueClear", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoaClient) QueueOffer(ctx context.Context, in *Value, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/github.com.vontikov.stoa.v1.Stoa/QueueOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoaClient) QueuePoll(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/github.com.vontikov.stoa.v1.Stoa/QueuePoll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoaClient) QueuePeek(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/github.com.vontikov.stoa.v1.Stoa/QueuePeek", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoaClient) DictionarySize(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/github.com.vontikov.stoa.v1.Stoa/DictionarySize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoaClient) DictionaryClear(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/github.com.vontikov.stoa.v1.Stoa/DictionaryClear", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoaClient) DictionaryPutIfAbsent(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/github.com.vontikov.stoa.v1.Stoa/DictionaryPutIfAbsent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoaClient) DictionaryPut(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/github.com.vontikov.stoa.v1.Stoa/DictionaryPut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoaClient) DictionaryGet(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/github.com.vontikov.stoa.v1.Stoa/DictionaryGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoaClient) DictionaryRemove(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/github.com.vontikov.stoa.v1.Stoa/DictionaryRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoaClient) DictionaryScan(ctx context.Context, in *Name, opts ...grpc.CallOption) (Stoa_DictionaryScanClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Stoa_serviceDesc.Streams[0], "/github.com.vontikov.stoa.v1.Stoa/DictionaryScan", opts...)
	if err != nil {
		return nil, err
	}
	x := &stoaDictionaryScanClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Stoa_DictionaryScanClient interface {
	Recv() (*KeyValue, error)
	grpc.ClientStream
}

type stoaDictionaryScanClient struct {
	grpc.ClientStream
}

func (x *stoaDictionaryScanClient) Recv() (*KeyValue, error) {
	m := new(KeyValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stoaClient) MutexTryLock(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/github.com.vontikov.stoa.v1.Stoa/MutexTryLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoaClient) MutexUnlock(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/github.com.vontikov.stoa.v1.Stoa/MutexUnlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoaClient) Keep(ctx context.Context, opts ...grpc.CallOption) (Stoa_KeepClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Stoa_serviceDesc.Streams[1], "/github.com.vontikov.stoa.v1.Stoa/Keep", opts...)
	if err != nil {
		return nil, err
	}
	x := &stoaKeepClient{stream}
	return x, nil
}

type Stoa_KeepClient interface {
	Send(*Ping) error
	Recv() (*Status, error)
	grpc.ClientStream
}

type stoaKeepClient struct {
	grpc.ClientStream
}

func (x *stoaKeepClient) Send(m *Ping) error {
	return x.ClientStream.SendMsg(m)
}

func (x *stoaKeepClient) Recv() (*Status, error) {
	m := new(Status)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StoaServer is the server API for Stoa service.
// All implementations must embed UnimplementedStoaServer
// for forward compatibility
type StoaServer interface {
	QueueSize(context.Context, *Name) (*Value, error)
	QueueClear(context.Context, *Name) (*Empty, error)
	QueueOffer(context.Context, *Value) (*Result, error)
	QueuePoll(context.Context, *Name) (*Value, error)
	QueuePeek(context.Context, *Name) (*Value, error)
	DictionarySize(context.Context, *Name) (*Value, error)
	DictionaryClear(context.Context, *Name) (*Empty, error)
	DictionaryPutIfAbsent(context.Context, *KeyValue) (*Result, error)
	DictionaryPut(context.Context, *KeyValue) (*Value, error)
	DictionaryGet(context.Context, *Key) (*Value, error)
	DictionaryRemove(context.Context, *Key) (*Result, error)
	DictionaryScan(*Name, Stoa_DictionaryScanServer) error
	MutexTryLock(context.Context, *Id) (*Result, error)
	MutexUnlock(context.Context, *Id) (*Result, error)
	Keep(Stoa_KeepServer) error
	mustEmbedUnimplementedStoaServer()
}

// UnimplementedStoaServer must be embedded to have forward compatible implementations.
type UnimplementedStoaServer struct {
}

func (UnimplementedStoaServer) QueueSize(context.Context, *Name) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueSize not implemented")
}
func (UnimplementedStoaServer) QueueClear(context.Context, *Name) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueClear not implemented")
}
func (UnimplementedStoaServer) QueueOffer(context.Context, *Value) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueOffer not implemented")
}
func (UnimplementedStoaServer) QueuePoll(context.Context, *Name) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueuePoll not implemented")
}
func (UnimplementedStoaServer) QueuePeek(context.Context, *Name) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueuePeek not implemented")
}
func (UnimplementedStoaServer) DictionarySize(context.Context, *Name) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictionarySize not implemented")
}
func (UnimplementedStoaServer) DictionaryClear(context.Context, *Name) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictionaryClear not implemented")
}
func (UnimplementedStoaServer) DictionaryPutIfAbsent(context.Context, *KeyValue) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictionaryPutIfAbsent not implemented")
}
func (UnimplementedStoaServer) DictionaryPut(context.Context, *KeyValue) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictionaryPut not implemented")
}
func (UnimplementedStoaServer) DictionaryGet(context.Context, *Key) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictionaryGet not implemented")
}
func (UnimplementedStoaServer) DictionaryRemove(context.Context, *Key) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DictionaryRemove not implemented")
}
func (UnimplementedStoaServer) DictionaryScan(*Name, Stoa_DictionaryScanServer) error {
	return status.Errorf(codes.Unimplemented, "method DictionaryScan not implemented")
}
func (UnimplementedStoaServer) MutexTryLock(context.Context, *Id) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MutexTryLock not implemented")
}
func (UnimplementedStoaServer) MutexUnlock(context.Context, *Id) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MutexUnlock not implemented")
}
func (UnimplementedStoaServer) Keep(Stoa_KeepServer) error {
	return status.Errorf(codes.Unimplemented, "method Keep not implemented")
}
func (UnimplementedStoaServer) mustEmbedUnimplementedStoaServer() {}

// UnsafeStoaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoaServer will
// result in compilation errors.
type UnsafeStoaServer interface {
	mustEmbedUnimplementedStoaServer()
}

func RegisterStoaServer(s *grpc.Server, srv StoaServer) {
	s.RegisterService(&_Stoa_serviceDesc, srv)
}

func _Stoa_QueueSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoaServer).QueueSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.vontikov.stoa.v1.Stoa/QueueSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoaServer).QueueSize(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoa_QueueClear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoaServer).QueueClear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.vontikov.stoa.v1.Stoa/QueueClear",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoaServer).QueueClear(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoa_QueueOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoaServer).QueueOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.vontikov.stoa.v1.Stoa/QueueOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoaServer).QueueOffer(ctx, req.(*Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoa_QueuePoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoaServer).QueuePoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.vontikov.stoa.v1.Stoa/QueuePoll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoaServer).QueuePoll(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoa_QueuePeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoaServer).QueuePeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.vontikov.stoa.v1.Stoa/QueuePeek",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoaServer).QueuePeek(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoa_DictionarySize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoaServer).DictionarySize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.vontikov.stoa.v1.Stoa/DictionarySize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoaServer).DictionarySize(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoa_DictionaryClear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoaServer).DictionaryClear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.vontikov.stoa.v1.Stoa/DictionaryClear",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoaServer).DictionaryClear(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoa_DictionaryPutIfAbsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoaServer).DictionaryPutIfAbsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.vontikov.stoa.v1.Stoa/DictionaryPutIfAbsent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoaServer).DictionaryPutIfAbsent(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoa_DictionaryPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoaServer).DictionaryPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.vontikov.stoa.v1.Stoa/DictionaryPut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoaServer).DictionaryPut(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoa_DictionaryGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoaServer).DictionaryGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.vontikov.stoa.v1.Stoa/DictionaryGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoaServer).DictionaryGet(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoa_DictionaryRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoaServer).DictionaryRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.vontikov.stoa.v1.Stoa/DictionaryRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoaServer).DictionaryRemove(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoa_DictionaryScan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Name)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoaServer).DictionaryScan(m, &stoaDictionaryScanServer{stream})
}

type Stoa_DictionaryScanServer interface {
	Send(*KeyValue) error
	grpc.ServerStream
}

type stoaDictionaryScanServer struct {
	grpc.ServerStream
}

func (x *stoaDictionaryScanServer) Send(m *KeyValue) error {
	return x.ServerStream.SendMsg(m)
}

func _Stoa_MutexTryLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoaServer).MutexTryLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.vontikov.stoa.v1.Stoa/MutexTryLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoaServer).MutexTryLock(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoa_MutexUnlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoaServer).MutexUnlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.vontikov.stoa.v1.Stoa/MutexUnlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoaServer).MutexUnlock(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoa_Keep_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoaServer).Keep(&stoaKeepServer{stream})
}

type Stoa_KeepServer interface {
	Send(*Status) error
	Recv() (*Ping, error)
	grpc.ServerStream
}

type stoaKeepServer struct {
	grpc.ServerStream
}

func (x *stoaKeepServer) Send(m *Status) error {
	return x.ServerStream.SendMsg(m)
}

func (x *stoaKeepServer) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Stoa_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.vontikov.stoa.v1.Stoa",
	HandlerType: (*StoaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueueSize",
			Handler:    _Stoa_QueueSize_Handler,
		},
		{
			MethodName: "QueueClear",
			Handler:    _Stoa_QueueClear_Handler,
		},
		{
			MethodName: "QueueOffer",
			Handler:    _Stoa_QueueOffer_Handler,
		},
		{
			MethodName: "QueuePoll",
			Handler:    _Stoa_QueuePoll_Handler,
		},
		{
			MethodName: "QueuePeek",
			Handler:    _Stoa_QueuePeek_Handler,
		},
		{
			MethodName: "DictionarySize",
			Handler:    _Stoa_DictionarySize_Handler,
		},
		{
			MethodName: "DictionaryClear",
			Handler:    _Stoa_DictionaryClear_Handler,
		},
		{
			MethodName: "DictionaryPutIfAbsent",
			Handler:    _Stoa_DictionaryPutIfAbsent_Handler,
		},
		{
			MethodName: "DictionaryPut",
			Handler:    _Stoa_DictionaryPut_Handler,
		},
		{
			MethodName: "DictionaryGet",
			Handler:    _Stoa_DictionaryGet_Handler,
		},
		{
			MethodName: "DictionaryRemove",
			Handler:    _Stoa_DictionaryRemove_Handler,
		},
		{
			MethodName: "MutexTryLock",
			Handler:    _Stoa_MutexTryLock_Handler,
		},
		{
			MethodName: "MutexUnlock",
			Handler:    _Stoa_MutexUnlock_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DictionaryScan",
			Handler:       _Stoa_DictionaryScan_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Keep",
			Handler:       _Stoa_Keep_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stoa.proto",
}
